/*
 * Interplanetary Fund — Copyright © 2026 Michelle Rogers. All Rights Reserved.
 * PROPRIETARY AND CONFIDENTIAL. Do not copy, distribute, or modify without
 * express written permission. See LICENSE file for full terms.
 */

import { query, mutation } from "./_generated/server";
import { v } from "convex/values";

// Verified Interplanetary Fund agent roster
// 7 production agents: fundraising, story, donor_relations, protocol, analytics, treasury, platform_sync
const REAL_AGENTS = [
  {
    name: "Fundraising Agent",
    role: "fundraising",
    purpose: "Campaign optimization, donor acquisition strategy, and fundraising execution support.",
    description: "Monitors campaign performance and recommends fundraising actions to improve conversion and momentum.",
    specialization: "Campaign optimization",
    status: "active",
    trustScore: 82,
    reliabilityScore: 84,
    efficiencyScore: 85,
    collaborationScore: 83,
    capabilities: ["campaign optimization", "donor outreach strategy", "milestone planning", "conversion tracking"],
    knowledgeAreas: ["fundraising strategy", "donor psychology", "campaign lifecycle"],
    responsibilities: ["optimize campaign performance", "recommend donor strategies", "track fundraising progress"],
    allowedActions: ["recommend_fundraising_actions", "set_campaign_milestones", "track_revenue"],
    restrictedActions: ["delete_campaign", "modify_payments"],
    permissions: ["read_campaigns", "write_recommendations", "track_revenue"],
    toolsAvailable: ["campaign optimizer", "revenue tracker", "milestone planner"],
    workflowAccess: ["campaign", "fundraising", "revenue"],
    dataAccessLevel: "write",
    approvalRequired: true,
    accentColor: "#22c55e",
    version: 2,
  },
  {
    name: "Story Agent",
    role: "story",
    purpose: "Narrative crafting, story optimization, and donor-facing messaging clarity.",
    description: "Builds and improves campaign stories for emotional clarity, accessibility, and conversion impact.",
    specialization: "Narrative crafting",
    status: "active",
    trustScore: 80,
    reliabilityScore: 82,
    efficiencyScore: 85,
    collaborationScore: 78,
    capabilities: ["story optimization", "narrative refinement", "SEO writing", "accessibility compliance"],
    knowledgeAreas: ["donor psychology", "storytelling", "conversion optimization", "content strategy"],
    responsibilities: ["refine campaign narratives", "optimize story versions", "ensure SEO and accessibility"],
    allowedActions: ["update_story", "create_story_versions", "optimize_content"],
    restrictedActions: ["delete_campaign", "modify_payments"],
    permissions: ["read_campaigns", "write_stories", "create_recommendations"],
    toolsAvailable: ["story optimizer", "story versioner"],
    workflowAccess: ["campaign", "story"],
    dataAccessLevel: "write",
    approvalRequired: false,
    accentColor: "#f472b6",
    version: 2,
  },
  {
    name: "Donor Relations Agent",
    role: "donor_relations",
    purpose: "Donor engagement, retention strategy, and supporter relationship quality improvement.",
    description: "Focuses on donor communication quality, retention behavior, and supporter lifecycle touchpoints.",
    specialization: "Donor engagement",
    status: "active",
    trustScore: 81,
    reliabilityScore: 83,
    efficiencyScore: 82,
    collaborationScore: 84,
    capabilities: ["donor engagement", "retention planning", "supporter messaging", "relationship health tracking"],
    knowledgeAreas: ["donor psychology", "communications", "retention strategy", "supporter lifecycle"],
    responsibilities: ["improve donor retention", "recommend engagement campaigns", "monitor supporter response trends"],
    allowedActions: ["create_donor_engagement_recommendations", "track_supporter_interactions", "flag_retention_risks"],
    restrictedActions: ["delete_campaign", "modify_payments"],
    permissions: ["read_campaigns", "read_supporter_interactions", "write_recommendations"],
    toolsAvailable: ["engagement tracker", "retention analyzer", "message advisor"],
    dataAccessLevel: "write",
    workflowAccess: ["campaign", "donor_relations", "supporters"],
    approvalRequired: false,
    accentColor: "#06b6d4",
    version: 2,
  },
  {
    name: "Protocol Agent",
    role: "protocol",
    purpose: "Protocol compliance enforcement across all monitored campaigns.",
    description: "Audits campaigns against protocol standards and surfaces violations requiring corrective action.",
    specialization: "Compliance enforcement",
    status: "active",
    trustScore: 90,
    reliabilityScore: 90,
    efficiencyScore: 87,
    collaborationScore: 85,
    capabilities: ["protocol auditing", "violation detection", "compliance scoring", "auto-fix recommendations"],
    knowledgeAreas: ["protocol standards", "campaign compliance", "quality controls"],
    responsibilities: ["run compliance audits", "report protocol gaps", "recommend corrective actions"],
    allowedActions: ["audit_campaign_protocol", "flag_protocol_violations", "recommend_protocol_fixes"],
    restrictedActions: ["delete_campaign", "modify_payments"],
    permissions: ["read_campaigns", "write_protocol_reports", "execute_protocol_checks"],
    toolsAvailable: ["protocol auditor", "compliance checker", "report generator"],
    workflowAccess: ["campaign", "protocol", "reports"],
    dataAccessLevel: "write",
    approvalRequired: true,
    accentColor: "#ef4444",
    version: 2,
  },
  {
    name: "Analytics Agent",
    role: "analytics",
    purpose: "Performance analytics, revenue projection, and donor trend insight generation.",
    description: "Analyzes campaign and donor metrics to forecast outcomes and identify performance opportunities.",
    specialization: "Revenue projection",
    status: "active",
    trustScore: 86,
    reliabilityScore: 87,
    efficiencyScore: 88,
    collaborationScore: 84,
    capabilities: ["revenue forecasting", "trend analysis", "campaign diagnostics", "performance summarization"],
    knowledgeAreas: ["fundraising analytics", "data interpretation", "forecasting methods"],
    responsibilities: ["forecast campaign outcomes", "monitor KPI movement", "summarize portfolio health"],
    allowedActions: ["generate_analytics_report", "project_revenue", "flag_performance_trends"],
    restrictedActions: ["delete_campaign", "modify_payments"],
    permissions: ["read_campaigns", "read_transactions", "write_reports"],
    toolsAvailable: ["analytics dashboard", "forecast model", "trend scanner"],
    workflowAccess: ["campaign", "analytics", "reports"],
    dataAccessLevel: "write",
    approvalRequired: false,
    accentColor: "#8b5cf6",
    version: 2,
  },
  {
    name: "Treasury Agent",
    role: "treasury",
    purpose: "Treasury balance oversight, fee calculations, and payout readiness management.",
    description: "Tracks treasury balances and payout math while preserving gross-to-net accounting accuracy.",
    specialization: "Fee & payout management",
    status: "active",
    trustScore: 88,
    reliabilityScore: 89,
    efficiencyScore: 87,
    collaborationScore: 83,
    capabilities: ["fee calculation", "payout review", "balance aggregation", "transaction oversight"],
    knowledgeAreas: ["treasury operations", "payout workflows", "financial controls"],
    responsibilities: ["calculate payout outcomes", "track treasury balances", "monitor payout request status"],
    allowedActions: ["calculate_payout", "calculate_batch_payout", "aggregate_balances"],
    restrictedActions: ["delete_campaign", "publish_campaign"],
    permissions: ["read_transactions", "write_treasury_reports", "read_payout_requests"],
    toolsAvailable: ["payout calculator", "balance aggregator", "treasury ledger"],
    workflowAccess: ["treasury", "finance", "reports"],
    dataAccessLevel: "write",
    approvalRequired: true,
    accentColor: "#14b8a6",
    version: 2,
  },
  {
    name: "Platform Sync Agent",
    role: "platform_sync",
    purpose: "External platform integration monitoring and synchronization readiness tracking.",
    description: "Maintains visibility into connected external fundraising platforms and sync health.",
    specialization: "External integration",
    status: "active",
    trustScore: 84,
    reliabilityScore: 85,
    efficiencyScore: 86,
    collaborationScore: 84,
    capabilities: ["platform monitoring", "sync status tracking", "connection diagnostics", "integration reporting"],
    knowledgeAreas: ["platform integrations", "sync operations", "cross-platform campaign mapping"],
    responsibilities: ["monitor platform connection status", "track sync quality", "report integration issues"],
    allowedActions: ["scan_platform_connections", "report_sync_status", "flag_integration_errors"],
    restrictedActions: ["delete_campaign", "modify_payments"],
    permissions: ["read_platforms", "write_sync_reports", "read_campaigns"],
    toolsAvailable: ["platform monitor", "sync dashboard", "connection diagnostics"],
    workflowAccess: ["platforms", "campaign", "reports"],
    dataAccessLevel: "write",
    approvalRequired: true,
    accentColor: "#f59e0b",
    version: 2,
  },
];

// Real campaign data from Interplanetary Fund Base44 app
// 5 campaigns with actual external platform totals
const REAL_CAMPAIGNS = [
  {
    title: "Running against the wind",
    status: "draft",
    category: "disaster_relief",
    goalAmount: 5000,
    raisedAmount: 0,
    donorCount: 0,
    outreachEnabled: true,
    paymentActive: false,
    storyPresent: true,
    coverImagePresent: true,
    summary: "",
    fundraiserEventDescription: "",
    ifCampaignId: "6a6da9072cf99f50edfa0ff6",
    endDate: "2026-09-30",
    aiPriority: "emotional",
    aiTone: "",
    aiIdealDonors: "Woman's organizations new small business grants small investors",
    aiInterestedOrgs: "Private investors, Facebook groups",
    aiPlatforms: "Facebook, Instagram, TikTok, Email",
    // External platform totals
    externalRaised: 0,
    externalDonors: 0,
    platformCount: 9,
  },
  {
    title: "Random tester",
    status: "active",
    category: "creative",
    goalAmount: 1000,
    raisedAmount: 0,
    donorCount: 0,
    outreachEnabled: true,
    paymentActive: false,
    storyPresent: true,
    coverImagePresent: true,
    summary: "",
    fundraiserEventDescription: "Live creativity showcase and donor Q&A hosted by the organizer.",
    ifCampaignId: "6a6d22ddbb0808d7a7678385",
    endDate: "",
    aiPriority: "emotional",
    aiTone: "",
    aiIdealDonors: "",
    aiInterestedOrgs: "Facebook groups based around charity",
    aiPlatforms: "",
    // External: Patreon $500, 2 donors
    externalRaised: 500,
    externalDonors: 2,
    platformCount: 1,
  },
  {
    title: "Help",
    status: "active",
    category: "emergency",
    goalAmount: 5000,
    raisedAmount: 0,
    donorCount: 0,
    outreachEnabled: true,
    paymentActive: false,
    storyPresent: true,
    coverImagePresent: true,
    summary: "",
    fundraiserEventDescription: "",
    ifCampaignId: "6a6d21b7ae792f66e70f4c5d",
    endDate: "",
    aiPriority: "emotional",
    aiTone: "Factual",
    aiIdealDonors: "",
    aiInterestedOrgs: "",
    aiPlatforms: "Facebook",
    // External: Buy Me a Coffee $9,000, 4 donors
    externalRaised: 9000,
    externalDonors: 4,
    platformCount: 1,
  },
  {
    title: "Woman with a dream",
    status: "active",
    category: "business",
    goalAmount: 50000,
    raisedAmount: 0,
    donorCount: 0,
    outreachEnabled: true,
    paymentActive: false,
    storyPresent: true,
    coverImagePresent: true,
    summary: "Im seeking help to fund Ai integration for this ai based application and platform.",
    fundraiserEventDescription: "Community launch event introducing the AI fundraising platform mission.",
    ifCampaignId: "6a6d189083f8df0b86af5491",
    endDate: "2027-01-01",
    aiPriority: "professional",
    aiTone: "Conversational",
    aiIdealDonors: "Everyone",
    aiInterestedOrgs: "Im unsure please help with this.",
    aiPlatforms: "Facebook, Email, Instagram, LinkedIn",
    // External: Ko-fi $250, Spotfund $80
    externalRaised: 330,
    externalDonors: 0,
    platformCount: 6,
  },
  {
    title: "Help homeless get a conversion van",
    status: "draft",
    category: "housing",
    goalAmount: 10000,
    raisedAmount: 0,
    donorCount: 0,
    outreachEnabled: true,
    paymentActive: false,
    storyPresent: true,
    coverImagePresent: true,
    summary: "Housing a homeless person",
    fundraiserEventDescription: "",
    ifCampaignId: "6a6d219983f8df0b86af5492",
    endDate: "2026-09-30",
    aiPriority: "emotional",
    aiTone: "",
    aiIdealDonors: "",
    aiInterestedOrgs: "",
    aiPlatforms: "",
    externalRaised: 0,
    externalDonors: 0,
    platformCount: 0,
  },
];

// Real platform connections from Interplanetary Fund Base44 app
const REAL_PLATFORMS = [
  { platform: "bluesky", kind: "social", displayName: "Interplanetaryfund", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 0, externalDonorCount: 0, status: "connected", automationMode: "auto" },
  { platform: "patreon", kind: "crowdfunding", displayName: "Help build our shelter", campaignId: "6a6d22ddbb0808d7a7678385", externalTotal: 500, externalDonorCount: 2, status: "connected", automationMode: "manual" },
  { platform: "facebook", kind: "social", displayName: "Interplanetary Fund", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 0, externalDonorCount: 0, status: "connected", automationMode: "auto" },
  { platform: "kofi", kind: "crowdfunding", displayName: "Running against the wind", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 250, externalDonorCount: 0, status: "connected", automationMode: "manual" },
  { platform: "buymeacoffee", kind: "crowdfunding", displayName: "Lady luck in need", campaignId: "6a6d21b7ae792f66e70f4c5d", externalTotal: 9000, externalDonorCount: 4, status: "connected", automationMode: "auto" },
  { platform: "spotfund", kind: "crowdfunding", displayName: "Running against the wind", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 80, externalDonorCount: 0, status: "connected", automationMode: "ask" },
  { platform: "fundrazr", kind: "crowdfunding", displayName: "Running against the wind", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 0, externalDonorCount: 0, status: "connected", automationMode: "ask" },
  { platform: "indiegogo", kind: "crowdfunding", displayName: "Running against the wind", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 0, externalDonorCount: 0, status: "connected", automationMode: "draft" },
  { platform: "givesendgo", kind: "crowdfunding", displayName: "Running against the wind", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 0, externalDonorCount: 0, status: "connected", automationMode: "auto" },
  { platform: "kickstarter", kind: "crowdfunding", displayName: "Interplanetary Fund", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 0, externalDonorCount: 0, status: "connected", automationMode: "auto" },
  { platform: "gofundme", kind: "crowdfunding", displayName: "Interplanetary Fund", campaignId: "6a6d189083f8df0b86af5491", externalTotal: 0, externalDonorCount: 0, status: "connected", automationMode: "auto" },
];

export const seedRealData = mutation({
  args: {},
  handler: async (ctx) => {
    // Clear existing data
    const existingAgents = await ctx.db.query("agents").collect();
    for (const a of existingAgents) await ctx.db.delete(a._id);
    
    const existingCampaigns = await ctx.db.query("monitoredCampaigns").collect();
    for (const c of existingCampaigns) await ctx.db.delete(c._id);
    
    const existingPlatforms = await ctx.db.query("externalPlatforms").collect();
    for (const p of existingPlatforms) await ctx.db.delete(p._id);

    // Seed real agents
    for (const agent of REAL_AGENTS) {
      await ctx.db.insert("agents", {
        ...agent,
        tasksCompleted: 0,
        successfulOutcomes: 0,
        failedOutcomes: 0,
        longTermMemory: [`Synced from Base44 Interplanetary Fund app: ${new Date().toISOString()}`],
        workingMemory: [],
        managedCampaigns: [],
      });
    }

    // Seed real campaigns
    for (const camp of REAL_CAMPAIGNS) {
      await ctx.db.insert("monitoredCampaigns", {
        ...camp,
        lastSynced: new Date().toISOString(),
      });
    }

    // Seed real platform connections
    for (const plat of REAL_PLATFORMS) {
      await ctx.db.insert("externalPlatforms", {
        ...plat,
        externalUrl: "",
        lastSynced: new Date().toISOString(),
        lastError: "",
      });
    }

    return {
      agentsSeeded: REAL_AGENTS.length,
      campaignsSeeded: REAL_CAMPAIGNS.length,
      platformsSeeded: REAL_PLATFORMS.length,
      totalExternalRaised: REAL_PLATFORMS.reduce((sum, p) => sum + p.externalTotal, 0),
      timestamp: new Date().toISOString(),
    };
  },
});
